language: "en"
first_run: true
setup_completed: false

reanimation:
  require_special_item: true
  required_item: GOLDEN_APPLE
  duration_ticks: 100
  health_restored: 4
  cooldown: 60
  revive_cooldown: 60

knockout:
  enabled: true
  duration_seconds: 30
  movement_disabled: true
  use_particles: true
  heartbeat_sound: true
  blindness: true
  suicide_hold_seconds: 3
  weakness_level: 1
  fatigue_level: 1
  enable_commands_allowed: false
  allowed_commands:
    - msg
    - r
    - help
    - reanimatemc:help

execution:
  enabled: true
  hold_duration_ticks: 40
  message_broadcast: true

effects_on_revive:
  nausea: 5
  slowness: 10
  resistance: 10

prone:
  enabled: true
  allow_crawl: true
  crawl_slowness_level: 5
  auto_crawl: false

looting:
  enabled: true

tablist:
  enabled: true

npc_summon:
  enabled: true
  max_summons_per_player: 1
  summon_cooldown: 300
  offline_timeout: 300
  require_item: false
  required_item: NETHER_STAR
  item_to_summon_golem: GOLD_INGOT

